async function main(){
  await  fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await  fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await  fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000')
  await fetch('http://localhost:8000') 
}
main()